service: aws-ws-draw-guess
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-north-1
  environment:
    CONNECTION_DB_TABLE: ${self:service}-connectionTable
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'dynamodb:PutItem'
        - 'dynamodb:DeleteItem'
        - 'dynamodb:Scan'
        - 'dynamodb:UpdateItem'
      Resource:
        - Fn::GetAtt: [ConnectionTable, Arn]
    - Effect: 'Allow'
      Action:
        - 'execute-api:ManageConnections'
      Resource:
        - 'arn:aws:execute-api:*:*:**/@connections/*'

functions:
  connectHandler:
    handler: handlers.connectHandler
    events:
      - websocket:
          route: $connect
  disconnectHandler:
    handler: handlers.disconnectHandler
    events:
      - websocket:
          route: $disconnect
  defaultHandler:
    handler: handlers.defaultHandler
    events:
      - websocket:
          route: $default
  setNameHandler:
    handler: handlers.setNameHandler
    events:
      - websocket:
          route: setName
  guessHandler:
    handler: handlers.guessHandler
    events:
      - websocket:
          route: guess
  drawHandler:
    handler: handlers.drawHandler
    events:
      - websocket:
          route: draw
  clearHandler:
    handler: handlers.clearHandler
    events:
      - websocket:
          route: clear

resources:
  Resources:
    ConnectionTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:service}-connectionTable
